### ISSUE TITLE
support one line have more than one items？

### ISSUE THREAD

**Issue by raind33** [tangbc/vue-virtual-scroll-list#228] opened 2020-06-01 01:25 UTC
## Describe the feature request

A clear and concise description of what you want to happen. Or a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Comment by xanxuz** [comment] 2020-06-01 13:37
Duplicate of #168

**Comment by tangbc** [comment] 2020-06-04 01:42
This implementation is a little complicated, can you provide a more specific use or other library?

**Closed** 2020-06-19 23:31 UTC
Labels: suggestion
