### ISSUE TITLE
Perfomance slow down in empty vue-cli project

### ISSUE THREAD

**Issue by scarry1992** [tangbc/vue-virtual-scroll-list#93] opened 2019-03-22 08:07 UTC
Hello, I`m using your scroll-list and it's an awesome lib, but I see the perfomance slow down when I'm trying your examples in blank vue-cli project. Maybe you know what I am doing wrong? All code in new project is code of your item-mode example.
![my example](https://user-images.githubusercontent.com/6060984/54808692-0d161d00-4c92-11e9-9347-bea65d6615a7.gif)

**Comment by tangbc** [comment] 2019-03-22 08:38
Is other example also slow? such as `finite` ？

**Comment by tangbc** [comment] 2019-03-22 08:40
Or is `https://tangbc.github.io/vue-virtual-scroll-list/examples/item-mode/` same performance in your browser?

**Comment by scarry1992** [comment] 2019-03-22 08:44
@tangbc, thatnks for fast reply, yes, in all exaples same troubles.

**Comment by tangbc** [comment] 2019-03-22 08:46
What environment, vue version and browser?

**Comment by scarry1992** [comment] 2019-03-22 08:47
vue: 2.6.10, browser last chrome

**Comment by scarry1992** [comment] 2019-03-22 08:49
On cloned your examples everythink is ok, but in blank vue-cli project that situation

**Comment by scarry1992** [comment] 2019-03-22 08:50
Node.js is 11.8.0

**Comment by scarry1992** [comment] 2019-03-22 08:51
I tried on vue ^2.5.* and ^2.6.*

**Comment by tangbc** [comment] 2019-03-22 08:52
Maybe case by vue updating someting, let me check out, and it would be great if you could push your code in a public demo repo.

**Comment by scarry1992** [comment] 2019-03-22 08:53
3 min please, I push on github example

**Comment by scarry1992** [comment] 2019-03-22 08:56
@tangbc , https://github.com/scarry1992/list-example-vue

**Comment by scarry1992** [comment] 2019-03-22 09:22
@tangbc, Are you tried already?

**Comment by tangbc** [comment] 2019-03-22 09:30
The problem is that I push some unpublish code in master (include example code), `itemcount` prop is under developing. 😂

Now master code is confusion...

Your can choose:
1. Reference example to this commit: [v1.3.1](https://github.com/tangbc/vue-virtual-scroll-list/blob/v1.3.1/examples/item-mode/finite.vue#L15) and prop `items` changes to `itemdata`
2. Use v-for frag mode reference to: [here](https://github.com/tangbc/vue-virtual-scroll-list#using-by-npm-module) 
3. Wait next publish version with `itemcount`.

**Comment by scarry1992** [comment] 2019-03-22 09:39
I understud that and fix example. But I stil have same troubles. You can see it in my repo:)
`<VirtualList class="list"
            :size="50"
            :remain="remain"
            :bench="bench"
            :start="start"
            :item="item"
            :itemdata="itemdata"
            :itemprop="itemBinding"
        ></VirtualList>`

**Comment by scarry1992** [comment] 2019-03-22 10:32
@tangbc, can you confirm what you have no troubles on my example?

**Comment by tangbc** [comment] 2019-03-22 11:11
Yes, actually it's `item-mode`'s bug, I will fixed in next version, you can use v-for frag mode first:

```vue
<VirtualList class="list"
    :size="50"
    :remain="remain"
    :bench="bench"
    :start="start"
>
    <Item v-for="item in itemdata" v-bind:key="item.index" :index="item.index" />
</VirtualList>
```

Slow down performance when call `this.itemdata[i]` every createElement in [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/v1.3.1/index.js#L372).

**Comment by scarry1992** [comment] 2019-03-22 13:00
Ok then, I will wait for new release, thx. I don`t close this issue while you din`t release new version, ok?

**Comment by tangbc** [comment] 2019-03-22 13:01
Sure

**Comment by tangbc** [comment] 2019-03-24 01:01
@scarry1992 version 1.3.2 has published, you can try again.

New props change see: https://github.com/tangbc/vue-virtual-scroll-list#about-item-mode

**Comment by scarry1992** [comment] 2019-03-26 12:18
@tangbc, Hello. I tried new version and got perfomance boost in simple examples, but in my case with hight complexity list item I got same results item-mode with v-for. I can attach my case and maybe you can help to understand what I do wrong?

**Comment by tangbc** [comment] 2019-03-27 01:22
Please update your example repo, I will check it.

**Closed** 2019-04-03 23:09 UTC
Labels: question
